# This is a generated file. Not intended for manual editing.
services:
  auction-svc:
    build:
      context: "C:\\Users\\ChilufyaO\\source\\repos\\CarAuctionApp"
      dockerfile: "AuctionService/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\ChilufyaO\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\ChilufyaO\\.nuget\\packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "chilufya/auction-svc:dev"
    ports:
    - "127.0.0.1:57001:57100"
    - "127.0.0.1:57201:57300"
    volumes:
    - "C:\\Users\\ChilufyaO\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Users\\ChilufyaO\\source\\repos\\CarAuctionApp\\AuctionService:/app:rw"
    - "C:\\Users\\ChilufyaO\\source\\repos\\CarAuctionApp:/src:rw"
    - "C:\\Users\\ChilufyaO\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.2.3\\\
      Linux64:/riderDebugger"
    - "C:\\Users\\ChilufyaO\\AppData\\Local\\Programs\\Rider/bin:/riderLogsConf"
    - "C:\\Users\\ChilufyaO\\AppData\\Local\\JetBrains\\Rider2023.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2023_11_27_16_14_59:/riderLogs:rw"
    working_dir: "/app"
